### ISSUE TITLE
t

### ISSUE THREAD

**Issue by Gs-shy** [bingco-zhan/vue-form-dragger#3]

**Comment by bincooo** [comment]
不好意思，没有留意消息。代码在dev 分支哦

从 Windows 版邮件发送

发件人: Gs-shy
发送时间: 2021年8月20日 14:42
收件人: bingco-zhan/vue-form-dragger
抄送: Subscribed
主题: Re: [bingco-zhan/vue-form-dragger] 能分享下dev版本的demo吗：） (#3)

Closed #3.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
